ALTER TYPE "HuntCurrencyReason" ADD VALUE IF NOT EXISTS 'TUTORIAL_REWARD';

ALTER TABLE "HuntPlayerProfile"
  ADD COLUMN IF NOT EXISTS "huntTutorialStep" TEXT NOT NULL DEFAULT 'WELCOME',
  ADD COLUMN IF NOT EXISTS "huntTutorialState" JSONB;
