import type { ComponentType } from "react";
import {
  Award,
  Baby,
  BadgeCheck,
  BadgePercent,
  Banknote,
  Bath,
  Beef,
  Beer,
  BellRing,
  Bike,
  BookOpen,
  Boxes,
  Brain,
  BriefcaseBusiness,
  Brush,
  Building2,
  Bus,
  Cake,
  CalendarDays,
  Camera,
  Car,
  ChefHat,
  Circle,
  CircleDollarSign,
  Clapperboard,
  Clock,
  Coffee,
  Compass,
  Cookie,
  CreditCard,
  Croissant,
  Crown,
  Diamond,
  Dices,
  Dog,
  Dumbbell,
  Film,
  Flag,
  Flame,
  Flower2,
  FlaskConical,
  Gamepad2,
  Gem,
  Gift,
  GraduationCap,
  Handshake,
  Heart,
  HeartHandshake,
  HeartPulse,
  Home,
  Hourglass,
  IceCreamBowl,
  KeyRound,
  Landmark,
  Leaf,
  Lightbulb,
  MapPin,
  MapPinned,
  Medal,
  Milestone,
  MoonStar,
  Music,
  Paintbrush,
  Palette,
  ParkingCircle,
  PartyPopper,
  PawPrint,
  Pill,
  Pizza,
  Plane,
  QrCode,
  RadioTower,
  Rocket,
  Route,
  Salad,
  ScanLine,
  Scissors,
  ScrollText,
  ShieldCheck,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  SmilePlus,
  Smartphone,
  Soup,
  Sparkle,
  Sparkles,
  Sprout,
  Star,
  Stars,
  Store,
  Sunrise,
  Tags,
  Target,
  Ticket,
  TicketCheck,
  TimerReset,
  TrainFront,
  TreePine,
  Trophy,
  Truck,
  UtensilsCrossed,
  UsersRound,
  Wallet,
  WalletCards,
  WandSparkles,
  Waves,
  Wine,
  Wrench,
  Zap,
} from "lucide-react";

export type InternalIconGroup =
  | "achievements"
  | "loyalty"
  | "city"
  | "business"
  | "food"
  | "shopping"
  | "health"
  | "lifestyle"
  | "mobility"
  | "services"
  | "energy";

export type InternalIconOption = {
  value: string;
  label: string;
  group: InternalIconGroup;
  keywords?: string[];
};

export const INTERNAL_ICON_GROUPS: Record<InternalIconGroup, string> = {
  achievements: "Достижения",
  loyalty: "Лояльность",
  city: "Город и партнёры",
  business: "Бизнес",
  food: "Еда и напитки",
  shopping: "Покупки",
  health: "Здоровье",
  lifestyle: "Стиль и интересы",
  mobility: "Транспорт",
  services: "Сервисы",
  energy: "Энергия",
};

export const INTERNAL_ICON_GROUP_ORDER: Record<InternalIconGroup, number> = {
  achievements: 0,
  loyalty: 1,
  city: 2,
  business: 3,
  food: 4,
  shopping: 5,
  health: 6,
  lifestyle: 7,
  mobility: 8,
  services: 9,
  energy: 10,
};

export const INTERNAL_ICONS: Record<string, ComponentType<{ className?: string }>> = {
  Award,
  Baby,
  BadgeCheck,
  BadgePercent,
  Banknote,
  Bath,
  Beef,
  Beer,
  BellRing,
  Bike,
  BookOpen,
  Boxes,
  Brain,
  BriefcaseBusiness,
  Brush,
  Building2,
  Bus,
  Cake,
  CalendarDays,
  Camera,
  Car,
  ChefHat,
  Circle,
  CircleDollarSign,
  Clapperboard,
  Clock,
  Coffee,
  Compass,
  Cookie,
  CreditCard,
  Croissant,
  Crown,
  Diamond,
  Dices,
  Dog,
  Dumbbell,
  Film,
  Flag,
  Flame,
  Flower2,
  FlaskConical,
  Gamepad2,
  Gem,
  Gift,
  GraduationCap,
  Grid2x2: Boxes,
  Handshake,
  Heart,
  HeartHandshake,
  HeartPulse,
  Home,
  Hourglass,
  IceCreamBowl,
  KeyRound,
  Landmark,
  Leaf,
  Lightbulb,
  MapPin,
  MapPinned,
  Medal,
  Milestone,
  MoonStar,
  Music,
  Paintbrush,
  Palette,
  ParkingCircle,
  PartyPopper,
  PawPrint,
  Pill,
  Pizza,
  Plane,
  QrCode,
  RadioTower,
  Rocket,
  Route,
  Salad,
  ScanLine,
  Scissors,
  ScrollText,
  ShieldCheck,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  SmilePlus,
  Smartphone,
  Soup,
  Sparkle,
  Sparkles,
  Sprout,
  Star,
  Stars,
  Store,
  Sunrise,
  Tags,
  Target,
  Ticket,
  TicketCheck,
  TimerReset,
  TrainFront,
  TreePine,
  Trophy,
  Truck,
  UtensilsCrossed,
  UsersRound,
  Wallet,
  WalletCards,
  WandSparkles,
  Waves,
  Wine,
  Wrench,
  Zap,
};

const rawOptions: InternalIconOption[] = [
  { value: "Award", label: "Награда", group: "achievements" },
  { value: "BadgeCheck", label: "Проверено", group: "achievements" },
  { value: "Crown", label: "Корона", group: "achievements" },
  { value: "Diamond", label: "Алмаз", group: "achievements" },
  { value: "Gem", label: "Кристалл", group: "achievements" },
  { value: "Medal", label: "Медаль", group: "achievements" },
  { value: "ShieldCheck", label: "Щит", group: "achievements" },
  { value: "Star", label: "Звезда", group: "achievements" },
  { value: "Stars", label: "Созвездие", group: "achievements" },
  { value: "Trophy", label: "Кубок", group: "achievements" },

  { value: "BellRing", label: "Сигнал", group: "loyalty" },
  { value: "CircleDollarSign", label: "Монета", group: "loyalty" },
  { value: "Gift", label: "Подарок", group: "loyalty" },
  { value: "QrCode", label: "QR", group: "loyalty" },
  { value: "ScanLine", label: "Скан", group: "loyalty" },
  { value: "Tags", label: "Категории", group: "loyalty" },
  { value: "Ticket", label: "Билет", group: "loyalty" },
  { value: "TicketCheck", label: "Абонемент", group: "loyalty" },
  { value: "Wallet", label: "Кошелёк", group: "loyalty" },
  { value: "WalletCards", label: "Карты", group: "loyalty" },

  { value: "Boxes", label: "Набор", group: "city" },
  { value: "Compass", label: "Компас", group: "city" },
  { value: "Flag", label: "Флаг", group: "city" },
  { value: "Handshake", label: "Партнёры", group: "city" },
  { value: "Home", label: "Дом", group: "city" },
  { value: "Landmark", label: "Площадь", group: "city" },
  { value: "MapPin", label: "Пин", group: "city" },
  { value: "MapPinned", label: "Метка", group: "city" },
  { value: "Milestone", label: "Маршрут", group: "city" },
  { value: "Route", label: "Путь", group: "city" },

  { value: "Banknote", label: "Деньги", group: "business" },
  { value: "BriefcaseBusiness", label: "Бизнес", group: "business" },
  { value: "Building2", label: "Компания", group: "business" },
  { value: "CreditCard", label: "Оплата", group: "business" },
  { value: "Store", label: "Витрина", group: "business" },
  { value: "UsersRound", label: "Люди", group: "business" },

  { value: "Beef", label: "Мясо", group: "food" },
  { value: "Beer", label: "Бар", group: "food" },
  { value: "Cake", label: "Десерт", group: "food" },
  { value: "ChefHat", label: "Шеф", group: "food" },
  { value: "Coffee", label: "Кофе", group: "food" },
  { value: "Cookie", label: "Печенье", group: "food" },
  { value: "Croissant", label: "Выпечка", group: "food" },
  { value: "IceCreamBowl", label: "Мороженое", group: "food" },
  { value: "Pizza", label: "Пицца", group: "food" },
  { value: "Salad", label: "Салат", group: "food" },
  { value: "Soup", label: "Суп", group: "food" },
  { value: "UtensilsCrossed", label: "Еда", group: "food" },
  { value: "Wine", label: "Вино", group: "food" },

  { value: "BadgePercent", label: "Скидка", group: "shopping" },
  { value: "ShoppingBag", label: "Покупки", group: "shopping" },
  { value: "ShoppingCart", label: "Корзина", group: "shopping" },
  { value: "Shirt", label: "Одежда", group: "shopping" },

  { value: "Bath", label: "Спа", group: "health" },
  { value: "HeartPulse", label: "Здоровье", group: "health" },
  { value: "Pill", label: "Аптека", group: "health" },

  { value: "Baby", label: "Дети", group: "lifestyle" },
  { value: "BookOpen", label: "Книга", group: "lifestyle" },
  { value: "Brain", label: "Ум", group: "lifestyle" },
  { value: "Brush", label: "Творчество", group: "lifestyle" },
  { value: "Camera", label: "Кадр", group: "lifestyle" },
  { value: "Clapperboard", label: "Кино", group: "lifestyle" },
  { value: "Dices", label: "Игры", group: "lifestyle" },
  { value: "Dog", label: "Питомцы", group: "lifestyle" },
  { value: "Dumbbell", label: "Фитнес", group: "lifestyle" },
  { value: "Film", label: "Фильм", group: "lifestyle" },
  { value: "FlaskConical", label: "Эксперимент", group: "lifestyle" },
  { value: "Flower2", label: "Красота", group: "lifestyle" },
  { value: "Gamepad2", label: "Игра", group: "lifestyle" },
  { value: "GraduationCap", label: "Обучение", group: "lifestyle" },
  { value: "Heart", label: "Сердце", group: "lifestyle" },
  { value: "HeartHandshake", label: "Доверие", group: "lifestyle" },
  { value: "Leaf", label: "Эко", group: "lifestyle" },
  { value: "Music", label: "Музыка", group: "lifestyle" },
  { value: "Paintbrush", label: "Стиль", group: "lifestyle" },
  { value: "Palette", label: "Арт", group: "lifestyle" },
  { value: "PartyPopper", label: "Праздник", group: "lifestyle" },
  { value: "PawPrint", label: "Лапа", group: "lifestyle" },
  { value: "Scissors", label: "Ножницы", group: "lifestyle" },
  { value: "SmilePlus", label: "Настроение", group: "lifestyle" },
  { value: "TreePine", label: "Природа", group: "lifestyle" },

  { value: "Bike", label: "Велосипед", group: "mobility" },
  { value: "Bus", label: "Автобус", group: "mobility" },
  { value: "Car", label: "Авто", group: "mobility" },
  { value: "ParkingCircle", label: "Парковка", group: "mobility" },
  { value: "Plane", label: "Путешествие", group: "mobility" },
  { value: "TrainFront", label: "Поезд", group: "mobility" },
  { value: "Truck", label: "Доставка", group: "mobility" },

  { value: "Circle", label: "Круг", group: "services" },
  { value: "Grid2x2", label: "Сетка", group: "services" },
  { value: "Smartphone", label: "Смартфон", group: "services" },
  { value: "Wrench", label: "Сервис", group: "services" },

  { value: "CalendarDays", label: "Календарь", group: "energy" },
  { value: "Clock", label: "Время", group: "energy" },
  { value: "Flame", label: "Огонь", group: "energy" },
  { value: "Hourglass", label: "Песочные часы", group: "energy" },
  { value: "KeyRound", label: "Ключ", group: "energy" },
  { value: "Lightbulb", label: "Идея", group: "energy" },
  { value: "MoonStar", label: "Ночь", group: "energy" },
  { value: "RadioTower", label: "Башня", group: "energy" },
  { value: "Rocket", label: "Ракета", group: "energy" },
  { value: "ScrollText", label: "История", group: "energy" },
  { value: "Sparkle", label: "Искра", group: "energy" },
  { value: "Sparkles", label: "Сияние", group: "energy" },
  { value: "Sprout", label: "Рост", group: "energy" },
  { value: "Sunrise", label: "Рассвет", group: "energy" },
  { value: "Target", label: "Цель", group: "energy" },
  { value: "TimerReset", label: "Таймер", group: "energy" },
  { value: "WandSparkles", label: "Магия", group: "energy" },
  { value: "Waves", label: "Волна", group: "energy" },
  { value: "Zap", label: "Молния", group: "energy" },
];

export const INTERNAL_ICON_OPTIONS = rawOptions.sort((left, right) => {
  const groupDelta = INTERNAL_ICON_GROUP_ORDER[left.group] - INTERNAL_ICON_GROUP_ORDER[right.group];
  if (groupDelta !== 0) return groupDelta;
  return left.label.localeCompare(right.label, "ru");
});

export function getInternalIconOption(value?: string | null) {
  if (!value) return null;
  return INTERNAL_ICON_OPTIONS.find((option) => option.value === value) ?? null;
}

export function InternalIcon({
  icon,
  fallback = "Circle",
  className,
}: {
  icon?: string | null;
  fallback?: string;
  className?: string;
}) {
  const Icon = icon ? INTERNAL_ICONS[icon] ?? INTERNAL_ICONS[fallback] ?? Circle : INTERNAL_ICONS[fallback] ?? Circle;
  return <Icon className={className} />;
}
